apiVersion: v1
kind: Pod
metadata:
  name: db3
  namespace: dxc-ramesh
  labels:
    cm: cm1
spec:
  containers:
  - name: c1
    image: docker.io/mysql
    env:
    - name: MYSQL_DATABASE
      valueFrom:
        secretKeyRef:
          name: secret2
          key: dbname
    - name: MYSQL_ROOT_PASSWORD
      valueFrom:
        secretKeyRef:
          name: secret2
          key: password
