apiVersion: v1
kind: Pod
metadata:
  name: pod1
  namespace: dxc-ramesh
  labels:
    cm: cm1
spec:
  containers:
  - name: c1
    image: docker.io/nginx
    env:
    - name: hostname
      valueFrom:
        configMapKeyRef:
          name: cm1
          key: hostname
    - name: dish
      valueFrom:
        configMapKeyRef:
          name: cm1
          key: dish
