root@bse-docker-vdps:/microservices# cat ms.yaml
version: "3.9"
services:
  frontend:
    build:
      context: .
      dockerfile: ./Dockerfile-frontend
    container_name: frontend
    ports:
    - "9091:80"
    networks:
      net2:
         ipv4_address: 12.12.0.11
    volumes:
    - "/sourcecode:/var/www/html"
    depends_on:
      - backend
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile-backend
    container_name: backend
    environment:
    - MYSQL_ROOT_PASSWORD=123
    networks:
      net2:
         ipv4_address: 12.12.0.12
networks:
  net2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 12.12.0.0/24
          gateway: 12.12.0.1
