apiVersion: machine.openshift.io/v1beta1
kind: MachineSet
metadata:
  labels:
    machine.openshift.io/cluster-api-cluster: dxc-rmg56
  name: dxc-rmg56-worker1-ap-south-1a
  namespace: openshift-machine-api
spec:
  replicas: 1
  selector:
    matchLabels:
      machine.openshift.io/cluster-api-cluster: dxc-rmg56 
      machine.openshift.io/cluster-api-machineset: dxc-rmg56-worker1-ap-south-1a 
  template:
    metadata:
      labels:
        machine.openshift.io/cluster-api-cluster: dxc-rmg56  
        machine.openshift.io/cluster-api-machine-role: worker 
        machine.openshift.io/cluster-api-machine-type: worker 
        machine.openshift.io/cluster-api-machineset: dxc-rmg56-worker1-ap-south-1a 
    spec:
      metadata:
        labels:
          node-role.kubernetes.io/worker: "" 
      providerSpec:
        value:
          ami:
            id: ami-07b4271c5265d317d 
          apiVersion: awsproviderconfig.openshift.io/v1beta1
          blockDevices:
            - ebs:
                iops: 0
                volumeSize: 120
                volumeType: gp2
          credentialsSecret:
            name: aws-cloud-credentials
          deviceIndex: 0
          iamInstanceProfile:
            id: dxc-rmg56-worker-profile 
          instanceType: m4.large
          kind: AWSMachineProviderConfig
          placement:
            availabilityZone: ap-south-1a
            region: ap-south-1
          securityGroups:
            - filters:
                - name: tag:Name
                  values:
                    - dxc-rmg56-worker1-sg 
          subnet:
            filters:
              - name: tag:Name
                values:
                  - dxc-rmg56-private-ap-south-1a 
          tags:
            - name: kubernetes.io/cluster/dxc-rmg56 
              value: owned
          userDataSecret:
            name: worker-user-data
